const CURRENCIES_CODES = {
  RUB: '0',
  EUR: '1',
  USD: '2'
};
 const CURRENCIES_TYPES = {};
CURRENCIES_TYPES[CURRENCIES_CODES.RUB] = 'RUB'
CURRENCIES_TYPES[CURRENCIES_CODES.EUR] = 'EUR'
CURRENCIES_TYPES[CURRENCIES_CODES.USD] = 'USD'

export {
  CURRENCIES_CODES,
  CURRENCIES_TYPES
}